Attendance System/Controllers/CheckInCheckOutController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Attendance_System.Models;
using ClosedXML.Excel;

namespace Attendance_System.Controllers
{
    [Authorize]
    public class CheckInCheckOutController : Controller
    {
        private AttendanceDbContext db = new AttendanceDbContext();


        // GET: CheckInCheckOut
        public async Task<ActionResult> Index(string sortOrder)
        {
            //ViewBag.CheckInParm = String.IsNullOrEmpty(sortOrder) ? "checkin_desc" : "";
            //ViewBag.CheckOutSortParm = sortOrder == "CheckOut" ? "checkout_desc" : "CheckOut";
            //ViewBag.NameSortParm = sortOrder == "Name" ? "checkout_desc" : "CheckOut";

            //var checkinCheckouts = from c in db.CheckinCheckouts.Include(c => c.Person).Include(c => c.Department)
            //                       select c;

            var checkinCheckouts = db.CheckinCheckouts.Include(c => c.Person).Include(c => c.Department).OrderByDescending(c => c.Checkin);

            //switch (sortOrder)
            //{
            //    case "checkin_desc":
            //        checkinCheckouts = checkinCheckouts.OrderByDescending(s => s.LastName);
            //        break;
            //    case "CheckOut":
            //        checkinCheckouts = checkinCheckouts.OrderBy(s => s.EnrollmentDate);
            //        break;
            //    case "checkout_desc":
            //        checkinCheckouts = checkinCheckouts.OrderByDescending(s => s.EnrollmentDate);
            //        break;
            //    default:
            //        checkinCheckouts = checkinCheckouts.OrderBy(c => c.Checkin);
            //        break;
            //}

            return View(await checkinCheckouts.ToListAsync());
        }

        // GET: CheckInCheckOut/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckinCheckout checkinCheckout = await db.CheckinCheckouts.FindAsync(id);
            if (checkinCheckout == null)
            {
                return HttpNotFound();
            }
            return View(checkinCheckout);
        }

        // GET: CheckInCheckOut/Create
        public ActionResult Create()
        {
            ViewBag.PhoneNumberID = new SelectList(db.People, "PhoneNumberID", "FullName");
            ViewBag.DepartmentID = new SelectList(db.Departments, "ID", "Department1");
            return View();
        }

        // POST: CheckInCheckOut/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,PhoneNumberID,Checkin,Checkout,Purpose,Device,Comment,DepartmentID")] CheckinCheckout checkinCheckout)
        {
            if (ModelState.IsValid)
            {
                checkinCheckout.ID = Guid.NewGuid();
                db.CheckinCheckouts.Add(checkinCheckout);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.PhoneNumberID = new SelectList(db.People, "PhoneNumberID", "FullName", checkinCheckout.PhoneNumberID);
            ViewBag.DepartmentID = new SelectList(db.Departments, "ID", "Department1", checkinCheckout.DepartmentID);
            return View(checkinCheckout);
        }

        // GET: CheckInCheckOut/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckinCheckout checkinCheckout = await db.CheckinCheckouts.FindAsync(id);
            if (checkinCheckout == null)
            {
                return HttpNotFound();
            }
            ViewBag.PhoneNumberID = new SelectList(db.People, "PhoneNumberID", "FullName", checkinCheckout.PhoneNumberID);
            ViewBag.DepartmentID = new SelectList(db.Departments, "ID", "Department1", checkinCheckout.DepartmentID);
            return View(checkinCheckout);
        }

        // POST: CheckInCheckOut/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,PhoneNumberID,Checkin,Checkout,Purpose,Device,Comment,DepartmentID")] CheckinCheckout checkinCheckout)
        {
            if (ModelState.IsValid)
            {
                db.Entry(checkinCheckout).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.PhoneNumberID = new SelectList(db.People, "PhoneNumberID", "FullName", checkinCheckout.PhoneNumberID);
            ViewBag.DepartmentID = new SelectList(db.Departments, "ID", "Department1", checkinCheckout.DepartmentID);
            return View(checkinCheckout);
        }

        // GET: CheckInCheckOut/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CheckinCheckout checkinCheckout = await db.CheckinCheckouts.FindAsync(id);
            if (checkinCheckout == null)
            {
                return HttpNotFound();
            }
            return View(checkinCheckout);
        }

        // POST: CheckInCheckOut/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            CheckinCheckout checkinCheckout = await db.CheckinCheckouts.FindAsync(id);
            db.CheckinCheckouts.Remove(checkinCheckout);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        // GET: CheckInCheckOut
        public async Task<ActionResult> Reports()
        {
            var checkinCheckouts = db.CheckinCheckouts.Include(c => c.Person).Include(c => c.Department).OrderByDescending(c => c.Checkin).Where(c => c.Person.PhoneNumberID == null);
            var datestart = "00:00";
            var dateend = "23:59";
            ViewBag.SearchStartDate = $"{DateTime.Now.ToShortDateString()} {string.Format("0:HH:mm", datestart)}";
            ViewBag.SearchStartDate = $"{DateTime.Now.ToShortDateString()} {string.Format("0:HH:mm", dateend)}";
            ViewBag.SearchEndDate = $"{DateTime.Now.ToShortDateString()} 23:59";
            return View(await checkinCheckouts.ToListAsync());
        }

        //// POST: CheckInCheckOut/Delete/5
        //[HttpPost, ActionName("Reports")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> Reports(Guid id)
        //{
        //    CheckinCheckout checkinCheckout = await db.CheckinCheckouts.FindAsync(id);
        //    db.CheckinCheckouts.Remove(checkinCheckout);
        //    await db.SaveChangesAsync();
        //    return RedirectToAction("Index");
        //}

        // POST: CheckInCheckOut/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Reports(DateTime startdate, DateTime enddate, bool? isNotSignOut, string people, string search)
        {

            ViewBag.SearchStartDate = string.Format("{0:dd/MM/yyy HH:mm}", startdate);
            ViewBag.SearchEndDate = string.Format("{0:dd/MM/yyy HH:mm}", enddate);
            ViewBag.SearchString = search;
            ViewBag.NoSignOut = isNotSignOut;
            ViewBag.Person = people;

           
            if (isNotSignOut != true)
            {
                if (people == "employee")
                {
                    var checkinCheckout = db.CheckinCheckouts.Include(c => c.Person).Include(c => c.Department).Where(c => c.Checkin >= startdate && c.Checkin <= enddate && (c.Person.FullName.Contains(search) || c.Person.PhoneNumberID.Contains(search) || c.Purpose.Contains(search) || c.Person.EmployeeID.Contains(search) || c.Device.Contains(search)  || c.Comment.Contains(search)) && c.Person.EmployeeID != null);
                    return View(checkinCheckout.ToList());
                }
                else if (people == "other")
                {
                    var checkinCheckout = db.CheckinCheckouts.Include(c => c.Person).Include(c => c.Department).Where(c => c.Checkin >= startdate && c.Checkin <= enddate && (c.Person.FullName.Contains(search) || c.Person.PhoneNumberID.Contains(search) || c.Purpose.Contains(search) || c.Person.EmployeeID.Contains(search) || c.Device.Contains(search)  || c.Comment.Contains(search)) && c.Person.EmployeeID == null);
                    return View(checkinCheckout.ToList());
                }
                else
                {
                    var checkinCheckout = db.CheckinCheckouts.Include(c => c.Person).Include(c => c.Department).Where(c => c.Checkin >= startdate && c.Checkin <= enddate && (c.Person.FullName.Contains(search) || c.Person.PhoneNumberID.Contains(search) || c.Purpose.Contains(search) || c.Person.EmployeeID.Contains(search) || c.Device.Contains(search)  || c.Comment.Contains(search)));
                    return View(checkinCheckout.ToList());
                }
            }
            else if (isNotSignOut == true)
            {
                if (people == "employee")
                {

Attendance System/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html class="boon-400">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="content-type" content="text/plain; charset=UTF-8" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/style5.css">
    <link href="~/Content/css/all.css" rel="stylesheet" />


    <link rel="apple-touch-icon" sizes="180x180" href="~/Content/Icon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/Content/Icon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/Content/Icon/favicon-16x16.png">
    <link rel="manifest" href="~/Content/Icon/site.webmanifest">
    <link rel="mask-icon" href="~/Content/Icon/[]safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="theme-color" content="#ffffff">

    <link href="~/Content/datatables.css" rel="stylesheet" />

    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/datatables.js"></script>




    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body style="padding-top: 0px;" class="boon-400">
    <style>


        canvas {
            display: block;
            vertical-align: bottom;
        }

        #particles-js {
            position: absolute;
            width: 100%;
            height: 100%;
            background: #00356B;
        }

        .text {
            position: absolute;
            top: 50%;
            right: 50%;
            -webkit-transform: translate(50%, -50%);
            transform: translate(50%, -50%);
            color: #fff;
            max-width: 90%;
            padding: 2em 3em;
            background: rgba(0, 0, 0, 0.4);
            text-shadow: 0px 0px 2px #131415;
            font-family: 'Open Sans', sans-serif;
        }

        h1 {
            font-size: 2.25em;
            font-weight: 700;
            letter-spacing: -1px;
        }


        .sidebar-link, .sidebar-link:visited {
            text-decoration: none;
            color: #e74c3c;
            transition: 0.3s;
        }

            .sidebar-link:hover, .sidebar-link:focus {
                text-decoration: none;
                color: white;
            }

        .sidebar-link {
            color: #191919;
        }

        #sidebar .sidebar-header {
            padding: 20px;
            background: #e74c3c;
        }

        #sidebar {
            min-width: 250px;
            max-width: 250px;
            background: #e8e8e8;
            color: black;
            transition: all 0.6s cubic-bezier(0.945, 0.020, 0.270, 0.665);
            transform-origin: bottom left;
        }


            #sidebar ul.components {
                padding: 20px 0;
                border-bottom: none;
            }

            #sidebar ul li.active > a, a[aria-expanded="true"] {
                color: #fff;
                background: #c0392b;
            }

        ul ul a {
            font-size: 0.9em !important;
            padding-left: 30px !important;
            background: #e74c3c;
        }

        #sidebar ul li a:hover {
            color: white;
            background: #e74c3c;
        }
    </style>
    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                    @Html.Partial("_LoginPartial")
                </div>
            </div>
        </div>*@
    <div class="wrapper" style="margin-bottom: 0">
        <!-- Sidebar Holder -->
        <nav id="sidebar" style="margin-bottom: 0; padding-bottom: 0; padding-bottom: 0">
            <div class="sidebar-header" style="padding: 4px 16px">
                <h3 style="color: white">ລະບົບຈັດການຄົນເຂົ້າອອກ</h3>
            </div>
            <ul class="list-unstyled components" style="padding-top: 0; padding-bottom: 0">

                <li class="active">
                    <a href="@Url.Action("Index", "CheckInCheckOut")"  aria-expanded="false" class="sidebar-link"> <i class="fa fa-user"></i>&nbsp; ຄົນເຂົ້າ-ຄົນອອກ</a>
                    @*<a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle sidebar-link">ຄົນເຂົ້າ-ຄົນອອກ</a>*@
                    @*<ul class="collapse list-unstyled" id="homeSubmenu">
                            <li>
                                <a href="#">ຄົນນອກ</a>
                            </li>
                            <li>
                                <a href="#">ຄົນພາຍໃນບໍລິສັດ</a>
                            </li>
                            <li>
                                <a href="#">ແຂກ</a>
                            </li>
                        </ul>*@
                </li>
                <li>
                    @*<a href="#chekinchekouttime" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle sidebar-link">ເວລາເຂົ້າ-ອອກ</a>*@
                    <a href="@Url.Action("Reports", "CheckInCheckOut")"  aria-expanded="false" class="sidebar-link"> <i class="fa fa-table"></i> &nbsp; ລາຍງານ</a>
                    @*<ul class="collapse list-unstyled" id="chekinchekouttime">
                            <li>
                                <a href="#">ເວລາເຂົ້າ</a>
                            </li>
                            <li>
                                <a href="#">ເວລາອອກ</a>
                            </li>
                        </ul>*@
                </li>

                @*<li>
                    <a href="#chekinchekouttime" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle sidebar-link"> <i class="fa fa-line-chart"></i> ລາຍງານ</a>
                    <ul class="collapse list-unstyled" id="chekinchekouttime">
                        <li>
                            <a href="#">ເວລາເຂົ້າ</a>
                        </li>
                        <li>
                            <a href="#">ເວລາອອກ</a>
                        </li>
                    </ul>
                </li>*@
            </ul>

        </nav>
        <!-- Page Content Holder -->
        <div id="content" class="" style="padding-bottom: 0; margin-bottom: 0">
            @RenderBody()
        </div>

    </div>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    @*<!-- jQuery CDN - Slim version (=without AJAX) -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <!-- Popper.JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
        <!-- Bootstrap JS -->
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>*@

    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
                $(this).toggleClass('active');
            });
        });

    </script>


</body>
</html>